"use client";
import React from "react";
import type { ProductStock } from "@/scripts/Types";
import axios from "axios";
import classes from "@/styles/Admin.module.css";

interface ProductRead extends Omit<ProductStock, "flavor" | "id"> {
  ids?: string[];
  flavors?: string[];
}

export default function Read() {
  const [update, setUpdate] = React.useState<boolean>(false);
  const [productsShown, setProductsShown] = React.useState<ProductRead[]>([]);

  // get ALL products
  React.useEffect(() => {
    (async function () {
      let productResponse = await axios({
        url: "/api/products",
        method: "POST",
        data: { method: "read", category: "all" },
      });

      let products: ProductRead[] = productResponse.data.data;

      console.log("Products READ: \n", products);

      setProductsShown(products);
    })();
  }, [update]);

  return (
    <div>
      <h1>Read Products Table</h1>
      <button onClick={() => setUpdate((prev) => !prev)}>Refresh</button>
      {productsShown.map((item, i) => (
        <ProductRow product={item} key={i} />
      ))}
    </div>
  );
}

function ProductRow({ product }: { product: ProductRead }) {
  const [isEditMode, setIsEditMode] = React.useState(false);

  function deleteEntireProduct() {
    axios({
      url: "api/products",
      method: "DELETE",
      data: { name: product.name },
    })
      .then((res) => {
        console.log("IT WORKED! deleted");
        console.log(res.data);
      })
      .catch((err) => {
        console.error(err);
      });
  }

  if (isEditMode) {
    //EDIT MODE
    /* TO EDIT:
    - name: (has to remain unique)
    - flavor (can't be empty)
    - unitPrice (must be positive)
    - stock (must be positive)
    - imageUrl

    - description ?
    - salesPrice ?
    - category ?
    - isFeatured

    */
    return (
      <div
        style={{
          border: "1px solid green",
          padding: "20px",
          margin: "3px",
        }}
      >
        <p>SKU#:</p>
        {Array.isArray(product.ids) &&
          product.ids.map((id) => <span key={id}>{id}, </span>)}
        <p>
          Product: <strong>{product.name}</strong>
        </p>
        <p>Price: ${product.unitPrice}</p>
        {product.salesPrice && (
          <p style={{ color: "red" }}>Sale: ${product.salesPrice}</p>
        )}
        <p>Flavor: {product.flavors}</p>
        <img src={product.imageUrl} width="60" height="60" alt="image" />
        <h4 style={{ color: "blue" }}>In Stock: {product.stock}</h4>
      </div>
    );
  }

  // DISPLAY MODE
  return (
    <div
      style={{
        border: "1px solid green",
        padding: "20px",
        margin: "3px",
      }}
    >
      <p>SKU#:</p>
      {Array.isArray(product.ids) &&
        product.ids.map((id) => <span key={id}>{id}, </span>)}
      <p>
        Product: <strong>{product.name}</strong>
      </p>
      <p>Price: ${product.unitPrice}</p>
      {product.salesPrice && (
        <p style={{ color: "red" }}>Sale: ${product.salesPrice}</p>
      )}
      <p>Flavors:</p>
      <FlavorsCrud product={product} />
      <div>
        <img src={product.imageUrl} width="60" height="60" alt="image" />
      </div>
      <h4 style={{ color: "blue" }}>In Stock: {product.stock}</h4>
      <button onClick={deleteEntireProduct} style={{ color: "red" }}>
        Delete ENTIRE PRODUCT
      </button>
    </div>
  );
}

interface FlavorsProps {
  product: any;
}

function FlavorsCrud({ product }: FlavorsProps) {
  const [flavorsString, setFlavorsString] = React.useState<string>("");
  const [updatedFlavor, setUpdatedFlavor] = React.useState<string>("");
  const [editFlavor, setEditFlavor] = React.useState<string | undefined>();

  function addFlavors() {
    if (flavorsString.length === 0) return;

    let flavorsToAdd = flavorsString.split(",");
    // use {...product}
    let payload = {
      ...product,
    };
    // replace flavors
    payload.flavors = flavorsToAdd;
    // delete unnecessary ids (they'll be auto-generated by prisma)
    delete payload.ids;

    console.log("Add Flavor Payload: ", payload);

    //CREATE
    axios({
      url: "api/flavor",
      method: "POST",
      data: { method: "create", data: payload },
    })
      .then((res) => {
        console.log("added flavor: ", res);
      })
      .catch((e) => {
        console.error("Error adding flavor: ", e);
      });
  }

  function deleteFlavor(skuIndex: number) {
    // use product.NAME and FLAVOR to delete row
    const id = product.ids[skuIndex];
    axios({
      url: "api/flavor",
      method: "DELETE",
      data: { id },
    })
      .then((res) => {
        console.log("deleted flavor: ", res);
      })
      .catch((e) => {
        console.error("Error deleting flavor: ", e);
      });
  }

  function updateFlavor() {
    axios({
      url: "api/flavor",
      method: "POST",
      data: {
        method: "update",
        data: {
          name: product.name,
          oldFlavor: editFlavor,
          newFlavor: updatedFlavor,
        },
      },
    })
      .then((res) => {
        console.log("updated flavor: ", res);
        setEditFlavor(undefined);
        setUpdatedFlavor("");
      })
      .catch((e) => {
        console.error("Error updating flavor: ", e);
      });
  }
  // things you need: productName, flavors
  return (
    <div style={{ border: "1px solid yellow" }} className={classes.flavors}>
      {product.flavors.map((flavor: string, i: number) => {
        return (
          <div
            style={{
              border: "1px solid red",
              padding: "12px",
            }}
            key={i}
          >
            {editFlavor === flavor ? (
              <>
                <input
                  type="text"
                  onChange={(e) => setUpdatedFlavor(e.target.value)}
                  defaultValue={editFlavor}
                />
                <button onClick={updateFlavor} style={{ color: "green" }}>
                  ✔️
                </button>
              </>
            ) : (
              <div onClick={() => setEditFlavor(flavor)}> f: {flavor}</div>
            )}
            <button onClick={() => deleteFlavor(i)} style={{ color: "red" }}>
              X
            </button>
          </div>
        );
      })}
      {/* OUTSIDE MAP NOW */}

      <div>
        <label htmlFor="add-flavor">Add Flavor</label>
        <input
          id="add-flavor"
          name="add-flavor"
          type="text"
          placeholder="separate by commas (ie: Peach,Apple,Orange...)"
          onChange={(e) => setFlavorsString(e.target.value)}
        />
        <button onClick={addFlavors}>Add Flavor(s)</button>
      </div>
    </div>
  );
}
